[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "plothist"
authors = [
    {name = "Cyrille Praz", email = "code.cyrraz@protonmail.com"},
    {name = "Tristan Fillinger", email = "tristan.github@gmail.com"},
    ]
dynamic = ["version", "description"]
