[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "plothist"
authors = [
    {name = "Cyrille Praz", email = "code.cyrraz@protonmail.com"},
    {name = "Tristan Fillinger", email = "tristan.github@gmail.com"},
    ]
classifiers = [
"License :: OSI Approved :: BSD License",
]
dynamic = ["version", "description"]
requires-python = ">=3.7"
dependencies = [
    "boost-histogram~=1.3.1",
    "numpy>=1.14.5",
    "matplotlib>=3.0",
    "yaml>5.3.1",
    "pandas>1.3.5",
    "sklearn>1.0.2",
]

[project.urls]
Homepage = "https://github.com/cyrraz/plothist"
Documentation = "https://plothist.readthedocs.io/"
"Bug Tracker" = "https://github.com/cyrraz/plothist/issues"
